# Parsing the raw.csv generated by running lis2dh_cluster.py

with open('raw.csv', 'r') as infile:
  with open('parsed.csv', 'w') as outfile:
    
    # Read the first line (the column headers)
    headers = infile.readline()
    headers = headers.split(';')
    newheaders = []
    for header in headers:
      if header == 't': newheaders += ['t']
      else: newheaders += [header+'x', header+'y', header+'z']
    newheaders = newheaders.join(',')
    outfile.write(newheaders + '\n')
    
    # Read and parse all sequential lines
    